#!/bin/bash
set -e  # exit on errors

# log to file , see https://unix.stackexchange.com/a/145654/427788
exec &> >(tee commit.log)

echo -e "\033[48;5;16m\033[1;97mupdate local repo\033[0m"
git pull
git --no-pager diff --check

./rebuild

echo -e "\033[48;5;16m\033[1;97mupdate documentation\033[0m"
doxygen Doxyfile

echo "commit to git"
git add .
git add -f docs
printf '━%.0s' $(seq $(tput cols))
echo -e "\033[48;5;16m\033[1;97mAll tests run successful und documemtation updated.\nPlease use git commit now.\033[0m"
com
git push

